-- File: 02_staging.sql
-- Project: MTG Card Database
-- Description: Staging Table for ETL pipeline
-- Author: Dave Sonnie
-- Copyright (c) 2026 Dave Sonnie

-- STAGING Table
--
-- Create the Staging table if it doesn't already exist
CREATE TABLE IF NOT EXISTS staging_cards (
    "artist"                    TEXT,
    "artistIds"                 TEXT,
    "asciiName"                 TEXT,
    "attractionLights"          TEXT,
    "availability"              TEXT,
    "boosterTypes"              TEXT,
    "borderColor"               TEXT,
    "cardParts"                 TEXT,
    "colorIdentity"             TEXT,
    "colorIndicator"            TEXT,
    "colors"                    TEXT,
    "defense"                   TEXT,
    "duelDeck"                  TEXT,
    "edhrecRank"                TEXT,
    "edhrecSaltiness"           TEXT,
    "faceConvertedManaCost"     TEXT,
    "faceFlavorName"            TEXT,
    "faceManaValue"             TEXT,
    "faceName"                  TEXT,
    "finishes"                  TEXT,
    "flavorName"                TEXT,
    "flavorText"                TEXT,
    "frameEffects"              TEXT,
    "frameVersion"              TEXT,
    "hand"                      TEXT,
    "hasAlternativeDeckLimit"   TEXT,
    "hasContentWarning"         TEXT,
    "hasFoil"                   TEXT,
    "hasNonFoil"                TEXT,
    "isAlternative"             TEXT,
    "isFullArt"                 TEXT,
    "isFunny"                   TEXT,
    "isGameChanger"             TEXT,
    "isOnlineOnly"              TEXT,
    "isOversized"               TEXT,
    "isPromo"                   TEXT,
    "isRebalanced"              TEXT,
    "isReprint"                 TEXT,
    "isReserved"                TEXT,
    "isStarter"                 TEXT,
    "isStorySpotlight"          TEXT,
    "isTextless"                TEXT,
    "isTimeshifted"             TEXT,
    "keywords"                  TEXT,
    "language"                  TEXT,
    "layout"                    TEXT,
    "leadershipSkills"          TEXT,
    "life"                      TEXT,
    "loyalty"                   TEXT,
    "manaCost"                  TEXT,
    "manaValue"                 TEXT,
    "name"                      TEXT,
    "number"                    TEXT,
    "originalPrintings"         TEXT,
    "originalReleaseDate"       TEXT,
    "originalText"              TEXT,
    "otherFaceIds"              TEXT,
    "power"                     TEXT,
    "printings"                 TEXT,
    "promoTypes"                TEXT,
    "rarity"                    TEXT,
    "rebalancedPrintings"       TEXT,
    "relatedCards"              TEXT,
    "securityStamp"             TEXT,
    "setCode"                   TEXT,
    "side"                      TEXT,
    "signature"                 TEXT,
    "sourceProducts"            TEXT,
    "subsets"                   TEXT,
    "subtypes"                  TEXT,
    "supertypes"                TEXT,
    "text"                      TEXT,
    "toughness"                 TEXT,
    "type"                      TEXT,
    "types"                     TEXT,
    "uuid"                      TEXT,
    "variations"                TEXT,
    "watermark"                 TEXT
);